#!/bin/bash

function configure_cpan {
	PERLENV=$1
	mkdir -p $PERLENV/lib/perl5/CPAN
	sed "s#@@VIRTUAL_ENV@@#$PERLENV#g" <<MYCONFIG > $PERLENV/lib/perl5/CPAN/MyConfig.pm
\$CPAN::Config = {
  'applypatch' => q[],
  'auto_commit' => q[0],
  'build_cache' => q[100],
  'build_dir' => q[@@VIRTUAL_ENV@@/.cpan/build],
  'build_dir_reuse' => q[1],
  'build_requires_install_policy' => q[yes],
  'bzip2' => q[/bin/bzip2],
  'cache_metadata' => q[1],
  'check_sigs' => q[0],
  'colorize_debug' => q[cyan],
  'colorize_output' => q[1],
  'colorize_print' => q[blue],
  'colorize_warn' => q[red],
  'commandnumber_in_prompt' => q[1],
  'cpan_home' => q[@@VIRTUAL_ENV@@/.cpan],
  'curl' => q[],
  'ftp' => q[/usr/bin/ftp],
  'ftp_passive' => q[1],
  'ftp_proxy' => q[],
  'getcwd' => q[cwd],
  'gpg' => q[/usr/bin/gpg],
  'gzip' => q[/bin/gzip],
  'histfile' => q[@@VIRTUAL_ENV@@/.cpan/histfile],
  'histsize' => q[100],
  'http_proxy' => q[],
  'inactivity_timeout' => q[0],
  'index_expire' => q[1],
  'inhibit_startup_message' => q[0],
  'keep_source_where' => q[@@VIRTUAL_ENV@@/.cpan/sources],
  'load_module_verbosity' => q[v],
  'lynx' => q[],
  'make' => q[/usr/bin/make],
  'make_arg' => q[],
  'make_install_arg' => q[],
  'make_install_make_command' => q[/usr/bin/make],
  'makepl_arg' => q[],
  'mbuild_arg' => q[],
  'mbuild_install_arg' => q[],
  'mbuild_install_build_command' => q[./Build],
  'mbuildpl_arg' => q[],
  'ncftp' => q[],
  'ncftpget' => q[],
  'no_proxy' => q[],
  'pager' => q[/usr/bin/less -MRS],
  'patch' => q[/usr/bin/patch],
  'prefer_installer' => q[MB],
  'prefs_dir' => q[@@VIRTUAL_ENV@@/.cpan/prefs],
  'prerequisites_policy' => q[follow],
  'scan_cache' => q[atstart],
  'shell' => q[/bin/bash],
  'show_unparsable_versions' => q[0],
  'show_upload_date' => q[0],
  'show_zero_versions' => q[0],
  'tar' => q[/bin/tar],
  'tar_verbosity' => q[v],
  'term_is_latin' => q[0],
  'term_ornaments' => q[1],
  'test_report' => q[0],
  'unzip' => q[],
  'urllist' => [q[ftp://mirror.internode.on.net/pub/cpan/], q[http://cpan.schools.net.au/]],
  'use_sqlite' => q[1],
  'wget' => q[/usr/bin/wget],
  'yaml_load_code' => q[0],
  'yaml_module' => q[YAML],
};

1;

__END__
MYCONFIG
}

function install_lib_local {
	TARBALL_URL=http://search.cpan.org/CPAN/authors/id/G/GE/GETTY
	PERLENV=$1
	PATH=$PERLENV/bin:$PATH
	export PERL5LIB=$PERLENV/lib/perl5:$PERL5LIB
	export PERL_MB_OPT="--install_base $PERLENV"
	export PERL_MM_OPT="INSTALL_BASE=$PERLENV"
	export PERL_MM_USE_DEFAULT=1
	wget -O CHECKSUMS $TARBALL_URL/CHECKSUMS
	[ -f CHECKSUMS ] || exit
	PACKAGE_NAME=`grep "local-lib.*tar.gz" CHECKSUMS | sed 's#^.*\(local-lib-.*\.tar\.gz\).*$#\1#' | sort | tail -1`
	rm CHECKSUMS
	echo "Fetching $PACKAGE_NAME"
	wget -O local-lib.tar.gz "${TARBALL_URL}/${PACKAGE_NAME}"
	tar xzvf local-lib.tar.gz || exit
	cd local-lib-*
	[ -f Makefile.PL ] || exit 1
	perl Makefile.PL
	make test && make install
	cd ..
	rm -rf local-lib*
	unset TARBALL_URL
	eval $(perl -I${PERLENV}/lib/perl5 -Mlocal::lib=${PERLENV})
	}

function prepare_directories {
	mkdir -p $1/bin
	mkdir -p $1/lib
	mkdir -p $1/include
	mkdir -p $1/man
	mkdir -p $1/.cpan
	}

function install_perl_proxy {
	PERLENV=$1
	perlbin=`which perl`
	cat > ${PERLENV}/bin/perl << EOF
#!/bin/sh
PERLENV="${PERLENV}"
${perlbin} -I\$PERLENV/lib/perl5 -Mlocal::lib=\$PERLENV \$@
EOF
	chmod 755 $PERLENV/bin/perl
	rehash
	}

function perlize_this_virtualenv {
	cd $VIRTUAL_ENV
	prepare_directories $VIRTUAL_ENV
	configure_cpan $VIRTUAL_ENV
	install_lib_local $VIRTUAL_ENV
	install_perl_proxy $VIRTUAL_ENV
	cpan DBI
	cpan CPAN::SQLite
	cpan Digest::SHA
	cpan Module::Build
}

perlize_this_virtualenv
